openapi: 3.0.0
info:
  title: Football API
  version: 1.0.0
  description: API for football competitions, teams, and players.

servers:
  - url: http://localhost.std23106.com

paths:
  /competitions:
    post:
      summary: Create a new competition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Competition"
      responses:
        "201":
          description: Competition created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Competition"
    get:
      summary: Get a list of competitions
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: string
          description: The page number to retrieve.
        - name: pageSize
          in: query
          required: true
          schema:
            type: string
          description: The number of items per page.
      responses:
        "200":
          description: A list of competitions
          content:
            application/json:
              schema:
                type: object
                properties:
                  competitions:
                    type: array
                    items:
                      $ref: "#/components/schemas/Competition"
                  page:
                    type: string
                  pageSize:
                    type: string
                  totalPages:
                    type: string
  /teams:
    post:
      summary: Create a new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Team"
      responses:
        "201":
          description: Team created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Team"
    get:
      summary: Get a list of teams
      parameters:
        - name: teamName
          in: query
          required: false
          schema:
            type: string
          description: Filter teams by name.
        - name: page
          in: query
          required: true
          schema:
            type: string
          description: The page number to retrieve.
        - name: pageSize
          in: query
          required: true
          schema:
            type: string
          description: The number of items per page.
      responses:
        "200":
          description: A list of teams
          content:
            application/json:
              schema:
                type: object
                properties:
                  teams:
                    type: array
                    items:
                      $ref: "#/components/schemas/Team"
                  page:
                    type: string
                  totalPages:
                    type: string

  /players:
    post:
      summary: Create a new player
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Player"
      responses:
        "201":
          description: Player created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Player"

  /teams/{teamId}/players:
    get:
      summary: Get a list of players in a team
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the team.
        - name: playerName
          in: query
          required: false
          schema:
            type: string
          description: Filter players by name.
        - name: page
          in: query
          required: true
          schema:
            type: string
          description: The page number to retrieve.
        - name: pageSize
          in: query
          required: true
          schema:
            type: string
          description: The number of items per page.
      responses:
        "200":
          description: A list of players in the team
          content:
            application/json:
              schema:
                type: object
                properties:
                  players:
                    type: array
                    items:
                      $ref: "#/components/schemas/Player"
                  page:
                    type: string
                  pageSize:
                    type: string
                  totalPages:
                    type: string

components:
  schemas:
    Competition:
      type: object
      properties:
        name:
          type: string
        location:
          type: string

    Team:
      type: object
      properties:
        name:
          type: string
        slogan:
          type: string
        competitions:
          type: array
          items:
            type: string

    Player:
      type: object
      properties:
        name:
          type: string
        number:
          type: integer
        strongFoot:
          type: string
          enum:
            - Left
            - Right
